### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'src/utils/logs/roll-2023.10.09 .log' Emitted 'error' event on WriteStream in stance at:

### ISSUE THREAD

**Issue by SahilShidruk** [klaus-2/Hope-Public#25]
14:25:10:954]: LOG - Loading shard(s) }-

Hint: hit control+c anytime to enter RE PL.

node:events:491

throw er; // Unhandled 'error' ev

ent

Error: ENOENT: no such file or directory, open 'src/utils/logs/roll-2023.10.09 .log'
Emitted 'error' event on WriteStream in stance at:

at emitErrorNT (node: internal/strea ms/destroy: 151:8)

at emitErrorCloseNT (node: internal/ streams/destroy:116:3) {

errno: -2,

code: ENOENT

syscall: 'open',

path: 'src/utils/logs/roll-2023.10.09

.log'

}

Node.js v18.12.1

**Comment by BryanAlberts** [comment]
> 14:25:10:954]: LOG - Loading shard(s) }-
> 
> Hint: hit control+c anytime to enter RE PL.
> 
> node:events:491
> 
> throw er; // Unhandled 'error' ev
> 
> ent
> 
> Error: ENOENT: no such file or directory, open 'src/utils/logs/roll-2023.10.09 .log' Emitted 'error' event on WriteStream in stance at:
> 
> at emitErrorNT (node: internal/strea ms/destroy: 151:8)
> 
> at emitErrorCloseNT (node: internal/ streams/destroy:116:3) {
> 
> errno: -2,
> 
> code: ENOENT
> 
> syscall: 'open',
> 
> path: 'src/utils/logs/roll-2023.10.09
> 
> .log'
> 
> }
> 
> Node.js v18.12.1

dont waste ur time he will not provide help for you
